Remove usage of deprecated APIs to run with Gradle 7
Gradle 7 removes some APIs which have been marked as deprecated.
An example of such API is `sourceSet.compileConfigurationName`.
Testsets plugin uses some of the removed methods which casues build failures
with the following error message:
```
Caused by: java.lang.NoSuchMethodError:
'java.lang.String org.gradle.api.tasks.SourceSet.getCompileConfigurationName()'
```

Solves: #117